# Generated by Django 5.0.1 on 2026-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="application_resumes/"
            ),
        ),
    ]
